version: '3'

services:
  qdrant:
    image: qdrant/qdrant:v1.1.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant:/qdrant/storage
  
  backend:
    image: tfm-backend:1.0
    ports:
      - "8000:8000"
    environment:
      - QDRANT_CLUSTER_HOST=qdrant
      - QDRANT_CLUSTER_PORT=6333
    depends_on:
      - qdrant

  frontend:
    image: tfm-frontend:1.0
    ports:
      - "8501:8501"
    environment:
      - BACKEND_HOST=http://backend
      - BACKEND_PORT=8000
    depends_on:
      - backend